[[CANDE_COMMANDS_ALTER]]
=== anchor:CANDE_COMMANDS_ALTER[]ALTER

[[CANDE_COMMANDS_ALTER_SYNTAX]]
==== Syntax
Refer to the WFL Programming Reference Manual for the complete syntax diagrams.

[[CANDE_COMMANDS_ALTER_EXPLANATION]]
==== Explanation
The ALTER command changes the file attributes of a disk file.

Refer to the File Attributes Programming Reference Manual for more information
about the file attributes that can be specified in the ALTER command.

The ALTER command is processed by the Work Flow Language (WFL), not CANDE.
The command (and any text appearing on the same line) is passed unedited to WFL.
For a more detailed explanation, refer to the ALTER statement in the WFL
Programming Reference Manual.

[[CANDE_COMMANDS_ALTER_EXAMPLES]]
==== Examples

[[CANDE_COMMANDS_ALTER_EXAMPLES_EXAMPLE1]]
===== Example1
The following ALTER statement sets the LOCKEDFILE file attribute of a file FILEX:

----
ALTER FILEX (LOCKEDFILE=TRUE)
----

The LOCKEDFILE file attribute prevents the file FILEX from being removed or replaced,
and the file name from being changed.
