[[CANDE_COMMANDS_APASSWORD]]
=== anchor:CANDE_COMMANDS_APASSWORD[]APASSWORD

[[CANDE_COMMANDS_APASSWORD_SYNTAX]]
==== Syntax
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_APASSWORD_SYNTAX_OLDAPASSWORD]]
===== <old apassword>
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_APASSWORD_SYNTAX_NEWAPASSWORD]]
===== <new apassword>
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_APASSWORD_EXPLANATION]]
==== Explanation
The APASSWORD command allows the accesscode password to be changed for the
current accesscode of a session.

To change accesscode passwords, all or part of the required information can be
entered with the APASSWORD command. Any information not initially provided is
requested by CANDE. For verification purposes, the <new apassword> (new
accesscode password) must be entered twice.

To provide complete information, the following would be entered:

----
APASSWORD <old apassword> <new apassword> <new apassword>
----

This form changes the user’s accesscode password from the current accesscode
password (<old apassword>) to a new accesscode password (<new apassword>).

On systems with the Secure Access Control Module or Password Management
security packages, the accesscode passwords must be entered on separate lines (and
usually in protected fields), if the security option SECUREPASSWORD is set. The old
and new passwords must be entered on lines that are separate from the command
and from each other.

If APASSWORD or any other subset of the complete command is entered, CANDE
prompts the rest of the command.

*_Note:_* If the CASESENSITIVEPW security option is set, passwords must be entered in a case-sensitive form.

For additional information about accesscode passwords, refer to “User Identification
and Logging On” in Section 1, "General Information."

Any CANDE schedule sessions inherit the accesscode of the CANDE session. The
APASSWORD command is not valid within a CANDE schedule session. If a schedule
session contains an ACCESS command with an invalid accesscode, the schedule
session is aborted.

CANDE includes the accesscode in all log records about a session, particularly in logon
and log-off records.

[[CANDE_COMMANDS_APASSWORD_EXAMPLES]]
==== Examples

[[CANDE_COMMANDS_APASSWORD_EXAMPLES_EXAMPLE1]]
===== Example1
----
APASSWORD ESR
#ENTER NEW ACCESSCODE PASSWORD PLEASE.
EPR
#RE-ENTER NEW ACCESSCODE PASSWORD PLEASE.
EPR
#

APASSWORD OLDPW = NEWPW NEWPW
#
----
