[[CANDE_COMMANDS_CHARGE]]
=== anchor:CANDE_COMMANDS_CHARGE[]CHARGE

[[CANDE_COMMANDS_CHARGE_SYNTAX]]
==== Syntax
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_CHARGE_SYNTAX_CHARGECODE]]
===== <chargecode>
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_CHARGE_EXPLANATION]]
==== Explanation
The CHARGE command specifies a new chargecode at some point in a session.

When CHARGE is entered, the chargecode reverts to a null chargecode specification
unless USEDEFAULTCHARGE and CHARGEREQ, or just CHARGEREQ, are SET in the
USERDATAFILE entry for that usercode. If both USEDEFAULTCHARGE and
CHARGEREQ are SET, transmitting CHARGE causes the chargecode to revert to the
default chargecode. If CHARGEREQ (but not USEDEFAULTCHARGE) is SET in the
USERDATAFILE for the current usercode, and CHARGE is entered, an error message is
given.

When CHARGE <chargecode> is entered, the chargecode changes to the specified
<chargecode>. If CHARGEREQ is SET in the USERDATAFILE, <chargecode> must be
validated in the USERDATAFILE. If CHARGEREQ is not SET, any chargecode can be
entered; validation in the USERDATAFILE is not necessary. Specifying a new
chargecode provides a breakdown of system usage statistics incurred under the
previous chargecode. When a new chargecode is entered, the system usage statistics
for the session are set to zero as if the previous session had terminated and a new
one had begun.

For more information on chargecodes, refer to “User Identification and Logging On” in
Section 1, “General Information.” Refer to the Security Administration Guide for
further information on the USERDATAFILE.

[[CANDE_COMMANDS_CHARGE_EXAMPLES]]
==== Examples

[[CANDE_COMMANDS_CHARGE_EXAMPLES_EXAMPLE1]]
===== Example1
----
charge
#SESSION 3601 ET=9.0 PT=0.0 IO=0.0
#CONTINUE SESSION 3601 14:08:034/20/78

CHAR ME
#SESSION 3601 ET=7:47.2 PT=55.8 IO=57.1
#CONTINUE SESSION 3601 14:15:50 04/20/78

CHAR 12345678901234567
#SESSION 3601 ET=5:08.9 PT=0.5 IO=0.2
#CONTINUE SESSION 3601 14:20:59 04/20/78 
----
