[[CANDE_COMMANDS_help]]
=== anchor:CANDE_COMMANDS_HELP[]HELP

[[CANDE_COMMANDS_HELP_SYNTAX]]
==== Syntax
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_HELP_SYNTAX_BOOKNAME]]
===== <book name>
----
RAILROAD DIAGRAM HERE
----

[[CANDE_COMMANDS_HELP_EXPLANATION]]
==== Explanation
The HELP command enables you to access any help book generated by the Help
Utility. The explanation of the HELP command that follows assumes the CANDE help
book is the system default help book in use.

You can choose from several HELP command options to perform the following
general functions:

* Display help text for chosen keywords and topics.
* List the session and default help books that are available to you.
* Change the session help book.
* Print parts of help text.

You can use two kinds of commands to view help text:

* Use the CANDE HELP command and options to access a help book and to invoke help mode.
* Use the help mode commands to navigate the text of a help book.

Help mode is a method of viewing help text that is automatically invoked when the
CANDE HELP command is used to access a help book. Help mode has a set of
commands that are used to navigate help text. Help mode is discussed in greater
detail in the "Using Help Mode" section, which follows the descriptions of the CANDE
HELP command options.

[[CANDE_COMMANDS_HELP_EXPLANATION_ACCESSANDCHANGINGTHECURRENTHELPBOOKANDSESSIONHELPBOOK]]
===== Accessing and Changing the Current Help Book and Session Help Book
The help book you access when you use the HELP command depends on your host
system default help book setting. When you log on to CANDE, your session help book
is set to the default help book.

The session help book is accessed when you enter a HELP command without
specifying a help book name. The session help book becomes your current help book.

The current help book can be changed to another help book, which remains as the
current help book until you exit help mode. You can change your current help book by
using the following HELP command when in help mode:
----
HELP <keyword> IN <book name> ON <pack name>
----

Use the following command to change your session help book when in CANDE:
----
HELP = <book name> ON <pack name>
----

The pack name is optional if the desired help book resides on the pack specified in
your FAMILY statement.

For more information about setting session help books, refer to the ?BOOK
Configuration Control command in this manual.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS]]
===== Using the HELP Command and Command Options
The HELP command gives you access to any help book available to you. You can
display help text for specific keywords, topics, and references with the HELP
command. You can identify a particular help book you prefer to use (such as the
MARC help book), query the default and session help book names, and print portions
of help text.

The HELP command options that provide these functionalities are described in the
following paragraphs. The explanations for the HELP command options and
accompanying examples assume that the CANDE help book is the session help book.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_HELP]]
.HELP
Entering the HELP command with no specified options accesses the session help
book. If the session help book is the CANDE help book, then the HELP command
displays information about the CANDE HELP command and its features.

Entering HELP with no options is the same as entering HELP HELP (CANDE
automatically enters the second HELP when you enter the HELP command). If the
session help book is not the CANDE help book and the session help book does not
have the keyword HELP, then entering HELP might produce the following error
message:
----
KEYWORD NOT FOUND
----

[[CANDE_COMMANDS_HELP_EXPLANATION_KEYWORD]]
===== <keyword>
The keyword option enables you to specify a word or group of words to display help
text linked to that keyword. For example, to display help text for the LIST command,
enter the following statement at the CANDE prompt:
----
HELP LIST
----

A keyword can also display help text for a general CANDE topic. For example, you can
access help text for pseudostations by entering the following statement:
----
HELP PSEUDOSTATION
----

For a list of valid keywords, use the KEYS option, which is described later in this HELP
command description.

A partial entry of a keyword is valid if the shortened keyword is unique among other
keywords. For example, the keyword CHANGE can be abbreviated as CHAN to display
help text for the CHANGE command; however, CHA produces an error message,
because the letters are insufficient to distinguish the CHANGE command from the
CHARGE command.

Keywords made up of a group of words bounded by asterisks are called composite
keywords. Enter the composite keyword, including the asterisks, with the HELP
command.

A partial entry of a composite keyword is also valid if a sufficient part of the
composite keyword is entered to keep it unique from other keywords. For example,
the following composite keyword could be shortened and still display the associated
help text:
----
HELP *ACCESSCODES AND RECOVERY FILES*

HELP *ACCESSCODES AND REC*
----

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_KEYS]]
.KEYS
The KEYS option displays a list of all the keywords in a help book. This list is useful for
browsing general CANDE topics and CANDE commands.

Refer to "Using Help Mode" later in this description of the HELP command for
information about how to display the help text for a keyword.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_TOPICS]]
.TOPICS
The TOPICS option displays a list of all the section titles in a help book, which is similar
to a Table of Contents. Section titles and the nested levels of topics and subtopics are
displayed.

Refer to "Using Help Mode" later in this description of the HELP command for
information about how to display the help text for topics and subtopics.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_REFERENCES]]
.REFERENCES
The REFERENCES option displays a list of other help books that are referenced in the
help text. The referenced help book can be accessed to find additional information
about a topic. You can return to the previous help book from any of the referenced
help books.

Refer to "Using Help Mode" later in this description of the HELP command for
information about how to access other referenced help books.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_INBOOKNAME]]
.IN <book name>
The IN <book name> option enables you to specify a help book file name (and the
pack name on which the help book file resides if it is different from your default family
pack). The following example shows a HELP command with a specified help book file
name and pack name:

----
HELP FIND IN *BOOK/CANDE/ENGLISH ON PACK1
----

If you omit the language node of the help book file name, your session language is
used as the language node when help is requested. If the help book in the session
language is not available, you receive an error message indicating that the help book
cannot be found.

You can specify a pack name with the ON <pack name> option or you can omit the
pack name. If the pack name is not specified, your family specifications are applied.
If the help book file is not found, an error message is displayed.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_QM]]
.?
The question mark (?) option displays the session and default help book file names.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_ASTERISK]]
.*
The asterisk (*) option resets the session help book to the default help book.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_EQBOOKNAME]]
.= <book name>
The = <book name> option enables you to change the session help book with another
help book. You can specify a pack name if the help book resides on a pack other than
that specified in your FAMILY statement.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_REMOVE]]
.:REMOVE
The :REMOVE option of the = <book name> option is used to remove the specified
help book from the help book cache. The :REMOVE option is typically used when a
new help book is created and the older version of the help book is still in cache.

If the :REMOVE option is not used, continue to access the older version help book in
memory, even though a newer version help book exists on disk.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHEHELPCOMMANDANDCOMMANDOPTIONS_PRINTER]]
.:PRINTER
The :PRINTER option enables you to print the section of help text for the specified
keyword without entering help mode.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGHELPMODE]]
===== Using Help Mode
Help mode is invoked when the HELP command is issued to request help text. Help
mode has its own set of commands and is a convenient way to navigate through the
text of your current help book. Help-mode commands are not stored in the saved text
queue.

The description of help mode that follows assumes that the current help book is the
CANDE help book.

The following help mode topics are discussed in subsequent paragraphs:

* Starting and ending help mode
* Understanding the help mode screen
* Using the SPCFY key
* Navigating help text in help mode
* Selecting keywords and embedded keywords
* Selecting references and embedded references
* Accessing and changing the current and session help books

[[CANDE_COMMANDS_HELP_EXPLANATION_STARTINGANDENDINGHELPMODE]]
===== Starting and Ending Help Mode
You are placed in help mode when you enter one of the following HELP command and
options that request information from a help book:

* HELP
* HELP <keyword>
* HELP <keyword> IN <book name>
* HELP KEYS
* HELP TOPICS
* HELP REFERENCES

The following HELP command and options query, request, or change help book status,
but do not place you in help mode:

* HELP ?
* HELP *
* HELP = <book name>
* HELP = <book name> :REMOVE
* HELP <keyword> : PRINTER

You can exit help mode and return to your CANDE prompt by entering QUIT on the
Command line of the help-mode screen, or by placing the cursor on QUIT and pressing
the SPCFY key. BYE and EXIT are synonyms for QUIT but are not listed on the help
mode Option line.

[[CANDE_COMMANDS_HELP_EXPLANATION_UNDERSTANDINGTHEHELPMODESCREEN]]
===== Understanding the Help Mode Screen
The help mode screen is composed of a Command line, an Option line, an Error
Message line, and a help text display area.

* Command line +
You can enter help mode commands on this line to navigate help text. Enter a help
mode command and press the XMIT key to perform a help request. +
The first character position of the command line might be prefilled with a plus sign
(\+) or minus sign (–) when you are displaying a list of keywords or viewing help
text. +
The plus sign indicates that more information follows the current screen of text. +
The minus sign indicates that you have reached the end of the help text for the
keyword, and you may traverse backward through the text if you wish. While
scrolling backward, the minus sign indicates that there is more help text to scroll
through in that direction. +
If the first character position of the command line is not prefilled with a plus (+) or
minus (–) sign, this indicates that the entire help text for the keyword is displayed
on the screen. +
You can enter a help mode command on the command line at any time to perform
help text retrieval.

* Option line +
The Option line lists the help mode commands. You can enter the uppercase
letters of the command (or the entire command) and the plus (+) or minus (–) sign
on the help mode command line to perform the desired action. +
Another method of selecting a help mode command is to place the cursor on a
command and press the SPCFY key. More information about using the SPCFY key
follows in the "Using the SPCFY Key" section.

* Error message line +
Help mode error messages are displayed on the third line (the solid line below the
Options line) of the help mode screen. Typical error messages are "Keyword not
found," "No parent topic," and "No subtopics." +
The solid line remains when an error message is not displayed.

* Help text display area +
The remaining area of the help mode screen is reserved for displaying help text.
Up to 30 lines of help text can be displayed in this area.

[[CANDE_COMMANDS_HELP_EXPLANATION_USINGTHESPCFYKEY]]
===== Using the SPCFY Key
There is an alternate method of navigating help text that can be used instead of
entering a help mode command on the Command line. You place the cursor on a help
mode command and press the SPCFY key to execute the help mode command.

This method is also convenient for displaying help text of embedded keywords,
accessing other referenced help books, displaying help text from a list of keywords,
and displaying help text from a list of topics.

To select and execute a help mode command from the Options line, place the cursor
on the command and press the SPCFY key. To select keywords, topics, or references
displayed on the screen, place the cursor on the item and press the SPCFY key.

The SPCFY key can also be used at the home position to scroll through help text. If the
home position is prefilled with a plus sign (+) or minus sign (–), then pressing the
SPCFY key causes the help text to scroll one page forward or backward, respectively.

[[CANDE_COMMANDS_HELP_EXPLANATION_NAVIGATINGHELPTEXTINHELPMODE]]
===== Navigating Help Text in Help Mode
Several help mode commands enable you to navigate help text. These help mode
commands are described in Table 3–1.
To perform a help task, you can use the help mode commands in either of the
following ways:

* Enter the command or abbreviation (indicated by uppercased letters) on the command line and press the XMIT key.
* Place the cursor on the help mode command and press the SPCFY key.

|====
|Help Mode Commands |Action

|+ |Pages forward one screen of help text at a time. If a number is entered after the plus sign, the help text scrolls forward the indicated number of lines. +
For example, the following command scrolls help text forward 24 lines: +
+ 24

|- |Pages backward one screen of help text at a time. +
If a number is entered after the minus sign, the help text scrolls backward the indicated number of lines.
For example, the following command scrolls help text backward 18 lines: +
- 18

|Keys |Displays a list of all keywords and composite keywords in the help book.

|Back |Displays the section of help text prior to the currently viewed section.

|FOward |Displays the next section of help text that follows the section currently being viewed.

|PRev |Displays the previously viewed page of help text. The last 10
screens of help text are stored, so it is possible to return to the
last 10 screens of previously viewed help text.

|TOpics |Displays a list of all the section titles in a help book. This display is
similar to a Table of Contents in organization and structure.

|REf |Displays a list of all the references to other help books that are
defined in the current help book. +
To switch from your current help book to the referenced help
book and display the topics of the referenced help book, place the
cursor on the referenced help book name and press the SPCFY
key. +
To return to the previous help book, use one of the three
methods described in “Selecting References and Embedded
References” later in this section.

|PArnt |Displays the help text for the parent topic of the currently
displayed text. +
For example, a parent topic could have several subtopics. If you
are reading help text of a subtopic and want to go to the parent
topic, place the cursor on PARNT and press the SPCFY key.

|RLtd |Provides a list of names of help text sections that are related to
the section of text you are viewing. Structurally within a help
book, related topics are at the same heading level as the current
topic.

|SUb |Provides a list of names of help text sections that are subtopics of the current topic.

|QUit |Exits help mode. BYE and EXIT are synonyms of QUIT, but are not listed on the help mode Options line.

|REFResh |Refreshes a corrupted help mode screen. Although this help
mode command is not listed as one of the selections on the
Option line, it is a valid help mode command.

|HELP <keyword> |Accesses help text for a specific keyword while you are in help
mode. You can enter the CANDE command HELP <keyword> on
the help mode command line to display help text from the current
help book. +
Although this help mode command is not listed as one of the
selections on the Option line, it is a valid help mode command.

|HELP <keyword> IN <help book file name> |Accesses help text for a specific keyword from another help book
while you are in help mode. You can enter the CANDE command
HELP <keyword> IN <help book file name> on the help mode
command line to display help text from another help book. +
Although this help mode command is not listed as one of the
selections on the Option line, it is a valid help mode command.
|====

[[CANDE_COMMANDS_HELP_EXPLANATION_SELECTINGKEYWORDSANDEMBEDDEDKEYWORDS]]
===== Selecting Keywords and Embedded Keywords
To access help text for a particular keyword using the SPCFY key, perform the
following procedure:

. Use the KEys command to display a list of keywords from the current help book.
. Place the cursor on the keyword for which you want help text.
. Press the SPCFY key.

If you know the keyword of the help text you want (such as a CANDE command),
enter HELP and the keyword on the help mode command line and press the XMIT key.
An embedded keyword is a keyword that appears within help text. An embedded
composite keyword is delimited with asterisks (*). Single-word embedded keywords
might not be bounded by asterisks, but many are delimited with asterisks to assist
you in finding more information.

To display the help text for an embedded keyword, position the cursor on the
embedded keyword and press the SPCFY key, or enter the embedded keyword
(including the asterisks if it is a composite keyword) on the help mode command line.

[[CANDE_COMMANDS_HELP_EXPLANATION_SELECTINGREFERENCESANDEMBEDDEDREFERENCES]]
===== Selecting References and Embedded References
A list of references from the current help book appears when the REf command is
entered on the help mode command line. To select a topic from a referenced help
book, perform the following procedure:

. Use the REf command to display a list of references for the current help book.

. Place the cursor on the reference in which you want help text and press the
SPCFY key. A list of topics from the referenced help book is displayed. The
referenced help book becomes the current help book.

. Enter a help mode command to display help text from the new help book.

An embedded reference is a reference that appears within help text.

To display a list of topics from the referenced help book, position the cursor over the
embedded reference and press the SPCFY key. The referenced help book becomes
the current help book.

There are several ways to return to the previous help book from a referenced help
book.

* Enter HELP REFERENCES on the Command line and press the XMIT key. If a list
of references is displayed and the help book that you want is listed, place the
cursor on the help book name and press the SPCFY key.

* Enter HELP <keyword> IN <help book file name> on the Command line and press
the XMIT key. The help book file name in this HELP command is the name of the
help book you want to return to. +
For example, if you are displaying help text from another help book and want to
return to the CANDE help book, enter the following on the Command line: +

----
HELP TOPICS IN BOOK/CANDE/ENGLISH
----

The topics (Table of Contents) of the CANDE help book are displayed and you can
use your cursor to select help on any CANDE topic or CANDE command. You can
enter KEYS or a keyword in place of TOPICS in the HELP command.

* Enter PRev on the Command line to display previously viewed screens of help
text. Continue entering PRev until you return to the screen that contains the help
text from where you referenced your current help book. Enter KEys, TOpics, or
HELP <keyword> to display help text from the originating help book.

You are limited to ten previous screens of help text. If none of the ten screens
contain help text from the originating help book, then you must use the one of the
first two listed methods to return to the previous help book.



[[CANDE_COMMANDS_HELP_EXAMPLES]]
==== Examples

[[CANDE_COMMANDS_HELP_EXAMPLES_EXAMPLE1]]
===== Example1
----
HELP KEYS 
----
